implement basic authentication
ctc-uci/get-inspired-backend pull request #9
Opened 2022-12-06 00:38 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #4

2022-12-07 09:59 UTC, ctc-devops commented on app.js
> +const cookieParser = require('cookie-parser');
🚫 **[eslint]** <[import/order](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/order.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`cookie-parser` import should occur before import of `./routes/auth`
```suggestion
const cookieParser = require('cookie-parser');
const { authRouter } = require('./routes/auth');
```

2022-12-07 09:59 UTC, ctc-devops commented on firebase.js
> +const credentials = require('./firebase-adminsdk.json');
🚫 **[eslint]** <[import/newline-after-import](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/newline-after-import.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected 1 empty line after require statement not followed by another require.
```suggestion
const credentials = require('./firebase-adminsdk.json');

```

2022-12-07 09:59 UTC, ctc-devops commented on firebase.js
> +const credentials = require('./firebase-adminsdk.json');
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './firebase-adminsdk.json'.

2023-01-25 01:21 UTC, ctc-devops commented on firebase.js
> +const credentials = require('./firebase-adminsdk.json');
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './firebase-adminsdk.json'.

2023-01-25 01:21 UTC, ctc-devops commented on routes/user.js
> +    console.log('GET');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-01-25 06:24 UTC, ctc-devops commented on routes/user.js
> +    console.log(err.message);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-02-01 20:03 UTC, claudeisakeeb requested changes
Looks pretty good, just a few comments

One thing to note: We will have to use the verifyToken function in auth.js eventually. I think it's OK to not secure the backend until we do midfi (basically lofi lol) but lets see what alan thinks

2023-02-01 20:03 UTC, claudeisakeeb commented on server/schema/users.sql
> + -- (NOTE andrew): also double check if enum works & if roles are appropriate
Thanks for this note @leeaj8-uci 

Instead of VARCHAR can we change the role attribute type to be an ENUM (admin, editor, viewer)?

https://dev.mysql.com/doc/refman/8.0/en/enum.html

2023-02-01 20:03 UTC, claudeisakeeb commented on server/schema/users.sql
> +CREATE TABLE users(
Can we rename user_x to just x?

ie user_id --> id, user_role --> role 

I can see in the db that it's already the case, so you can just rename everything in this file

2023-02-01 20:03 UTC, claudeisakeeb commented on routes/user.js
> +    const { email, firstName, lastName, role, id } = req.body;
id is gotten from req.params not req.body

2023-02-01 20:03 UTC, claudeisakeeb commented on routes/user.js
> +    console.log('GET');
it's fine to have this for debugging for now imo

2023-02-01 20:03 UTC, claudeisakeeb commented on routes/auth.js
> +// File for routes/function restricting access
Let's renamed this to auth.route.js to keep it consistent with Kyle's

2023-02-01 20:03 UTC, claudeisakeeb commented on routes/user.js
> +// imports
Let's rename this to user.router.js to keep consistent with Kyle's

2023-02-06 00:47 UTC, merged